### ISSUE TITLE
.words() returns null elements

### ISSUE THREAD

**Issue by ndedic** [Marak/faker.js#214] opened 2015-05-27 10:16 UTC
words() method returns an array which may contain null values. Is this to be expected?
I am able to replicate it using faker.lorem.words() within 100 iterations or less.

{"keywords": faker.lorem.words()}
{"keywords":["molestias","aut",null]}

Thanks,
Nedim

**Comment by tkoomzaaskz** [comment] 2015-05-27 13:04
Nope, it's not expected :) I checked it and, in fact, undefined values are returned *sometimes*. But the real problem lines in the implementation of the ´Helpers.shuffle´ loop.

Will fix it soon.

**Comment by ndedic** [comment] 2015-05-27 13:27
Yes, I have managed to get that far but did not have enough time to unwrap .shuffle functionality :-)

**Comment by tkoomzaaskz** [comment] 2015-05-27 13:44
I'll handle that. Thank you for spotting the bug :)

The fix will be included in the upcoming release.

**Comment by ndedic** [comment] 2015-05-27 13:49
np

**Comment by tkoomzaaskz** [comment] 2015-05-27 16:50
@ndedic, the problem is in this line: https://github.com/Marak/faker.js/blob/a6c857f5b442d20182e64cf4f859e114d29a6786/lib/helpers.js#L42
The for loop is hardly readable, but the problem is that the faker.random.number(x) can take [0..x] and if it takes exactly `x` then accessing `x` index of the array will result in returning `undefined` instead of throwing an error (welcome to JavaScript). So if you randomly get the size of the collection in the first step, you'll get exactly one `undefined` in the result.

The code of the `shuffle` - bug-fixed and made more readable - should look like this:

```
function shuffle(o) {
  o = o || ["a", "b", "c"];
  for (var x, j, i = o.length - 1; i > 0; i--) {
    j = faker.random.number(i);
    x = o[i];
    o[i] = o[j];
    o[j] = x;
  }
  return o;
}
```

Anyway, we've just had a quarrel with the owner of this project and as a result all collaborators were removed from this project. Can't understand why, but that's what happened.

**Comment by sherrman** [comment] 2015-06-04 19:11
Thanks!

**Closed** 2015-06-11 12:36 UTC
Labels: Bug
