### ISSUE TITLE
npm publish latest version

### ISSUE THREAD

**Issue by h2non** [Marak/faker.js#604] opened 2018-02-07 20:02 UTC
`master` branch contains several fixes and features, such as `faker.unique` method, which is pretty handy. 

Can someone with privileges run `npm publish` a bumping the minor or major version?

Thanks.

**Comment by SolarKing** [comment] 2018-02-09 02:03
I second this! Trying to use `faker.date.soon`, which was implemented in May and the latest release was published in Feb. Even @types/faker has their [types for this module](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4fe726b4c93fed980570d706cc3e739c3a98e276/types/faker/index.d.ts) for the most part up-to-date :)

**Comment by conatus** [comment] 2018-02-19 16:33
I also hit the wall with `faker.date.soon`. I would be good to have this updated.

Thanks so much.

**Comment by rooterkyberian** [comment] 2018-03-22 11:33
Issues that would be resolved by releasing new version:
https://github.com/Marak/faker.js/issues/554
https://github.com/Marak/faker.js/issues/581
https://github.com/Marak/faker.js/issues/583

**Comment by thomasedwards** [comment] 2018-03-22 15:23
If you [compare master to v4.1.0](https://github.com/Marak/faker.js/compare/v4.1.0...master) there’s quite a few things missing going back to November 2015. Not sure if new versions are created from the old version, or from `master`, but hopefully all of these can be included – although there’s enough here to almost call it a minor revision!

**Comment by thomasedwards** [comment] 2018-03-22 15:27
Ah, just read the [#583 comment](https://github.com/Marak/faker.js/issues/583#issuecomment-353873245). So we know exactly what the problem is. Frustrating but must be respectful, will roll my own. Thanks.

**Comment by elie222** [comment] 2018-05-15 17:13
This should help:

```sh
yarn add git+ssh://git@github.com:Marak/faker.js.git#master
```

**Comment by rooterkyberian** [comment] 2018-05-16 11:56
Any reason why @elie2222 comment with workaround using yarn to install faker.js directly from github was removed?

**Comment by waldyrious** [comment] 2019-06-04 16:47
This issue is a duplicate of #692, per @Marak's [comment in #583](https://github.com/Marak/faker.js/issues/583#issuecomment-427478534).

@h2non, could you close this one so discussion can be focused in a single place? Thanks!

**Closed** 2019-06-05 11:37 UTC
