### ISSUE TITLE
faker.internet.url() generate invalid urls

### ISSUE THREAD

**Issue by xergioalex** [Marak/faker.js#317] opened 2015-12-13 14:15 UTC
For example this url is invalid: "'https://miguel ángel.com.es'".

**Comment by Marak** [comment] 2015-12-19 10:51
A pull request to fix this would be welcomed.

**Comment by yn5** [comment] 2015-12-29 18:07
@xergioalex Could you provide a reproduction path?

**Comment by yn5** [comment] 2015-12-29 18:14
@xergioalex Could you provide a reproduction path?

I've tried to find a case where faker.internet.url() would return a url with a space or an á in it with the following code but I couldn't find the issue like this.

```javascript
for (var i = 0; i < 1000000; i++) {
  a = faker.internet.url();
  if (/ |á/.test(a)) {
    console.log(a)
  }
}
```

**Comment by berrberr** [comment] 2015-12-29 22:33
@yn5 It's because @xergioalex is using a locale that can generate invalid URL characters from `faker.name.firstName()` (eg. [ES locale](https://github.com/Marak/faker.js/blob/master/lib/locales/es/name/first_name.js)).

The best fix is probably to replace the regex [here](https://github.com/Marak/faker.js/blob/master/lib/internet.js#L53) to reject everything _except_ valid URL characters.

**Comment by yn5** [comment] 2015-12-29 22:46
Thanks @berrberr. In that case this relates to https://github.com/Marak/faker.js/issues/283 and https://github.com/Marak/faker.js/issues/294. What about fixing all of them by implementing https://www.npmjs.com/package/urlify? We could delegate the creation of valid urls completely to a dedicated library that way. What do you think @Marak?

**Comment by Marak** [comment] 2016-03-03 09:49
@yn5 - I don't think I'd like to add 300 lines of code just for that functionality. 

Has this been fixed in master with https://github.com/Marak/faker.js/pull/326 ?

Do we need to modify the regex?

**Comment by Marak** [comment] 2018-10-15 05:30
Closing for inactivity.

Please feel free to add more information if you feel we should revisit this.

Thank you for your contributions.

**Closed by Marak** 2018-10-15 05:30 UTC
