### ISSUE TITLE
Problem with gender

### ISSUE THREAD

**Issue by IgnacioYanjari** [Marak/faker.js#677] opened 2018-08-04 21:08 UTC
I try to obtain a name with specific gender in NodeJs, but doesn't work.

what am I doing wrong?

```
    let genders = [ 'female' , 'male' ];
    let gender = faker.random.arrayElement(gender);
    let name = faker.name.firstName(genre);
```

**Comment by stoutlabs** [comment] 2018-08-05 11:59
Ah, you were close! Line 2 should be:
```javascript
let gender = faker.random.arrayElement(genders);
```
(This is because the array you created in line 1 is named ```genders```)

**Comment by Marak** [comment] 2018-08-05 12:05
I'd also make sure to test on `master` branch.

**Comment by IgnacioYanjari** [comment] 2018-08-05 22:16
@stoutlabs  soo close, but still doesn't work and it was my transcription error. 😢

**Comment by stoutlabs** [comment] 2018-08-06 00:48
@IgnacioYanjari  Hmm, I just tested your corrected code in the console at [https://rawgit.com/Marak/faker.js/master/examples/browser/index.html](https://rawgit.com/Marak/faker.js/master/examples/browser/index.html) and it worked fine for me. 

(Note: Subsequent calls to update gender and name worked as well.)

**Comment by stoutlabs** [comment] 2018-08-06 03:07
Haha, you are right - I can confirm this issue too. (I only tried 3 or 4 times previously, and must have gotten lucky!)

After looking at the source (at [/lib/name.js](https://github.com/Marak/faker.js/blob/master/lib/name.js)) at I even tried using numeric values for gender (0 for male, 1 for female) and still receive incorrect gendered names.

Digging further into console logs shows that ```faker.definitions.name.female_first_name``` and ```faker.definitions.name.male_first_name``` are both undefined... but I see them both defined  and exported in the 'en' locales folder.

**Comment by markreid** [comment] 2018-08-27 11:08
The `male_first_name` and `female_first_name` definitions for the `en` locale are in the master branch, but they're not in the 4.1.0 release, which is what npm will pull if you run `npm install faker`.

I'm not sure how actively maintained this project is, it looks like there's a few PRs open that haven't been merged, and there have been a few merges since the last official release. 

If you need to use the gendered name functions you can checkout the master branch and build yourself...

**Comment by stoutlabs** [comment] 2018-08-27 18:32
Ahhh, good catch on the NPM version not being the same as the current master branch! (That must be what the author was trying to say above.)

**Comment by rugk** [comment] 2019-09-26 09:54
Is there any news? Can't you just publish a release, @Marak?

**Comment by saniales** [comment] 2020-07-09 14:55
+1 for release

**Comment by ppanchal97** [comment] 2020-07-30 21:08
It looks like the issue still persists as of 30/07/2020. If you used `npm install faker` - your `package.json` file will always point to version `4.1.0`. This version does not contain the latest changes (last update ~2017) In order to use gendered names in your faker data- 
1. Point your `package.json` dependency to the github repository link as such:

```
  "dependencies": {
    "faker": "https://github.com/Marak/Faker.js"
  }
```

**Closed** 2020-08-24 03:18 UTC
