### ISSUE TITLE
Custom Email Addresses Not Generating Properly

### ISSUE THREAD

**Issue by olafwrieden** [Marak/faker.js#791] opened 2019-06-08 05:18 UTC
I am generating an email address based on the format `first.last@provider` and looked at the [wiki page](https://github.com/Marak/faker.js/wiki/Internet) for help.

**The Problem**
Docs show that `faker.internet.email("joe","smith","gmail.com");` will return `joe.smith@gmail.com`. However, that does not seem to be the case for me as it generated `joe.smith65@gmail.com` (note the extra numbers). _Is it just me or is this a bug?_

**This is my implementation of Faker.js:**
```javascript
let first_name = faker.name.firstName() // Returned: Joe
let last_name = faker.name.lastName() // Returned: Smith
const user = {
    first_name, // Set First Name: Joe
    last_name, // Set Last Name: Smith
    email_address: faker.internet.email(
        first_name, // Pass in: Joe
        last_name, // Pass in Smith
        faker.random.arrayElement(['gmail.com', 'hotmail.com']) // Let Faker.js choose
    ),
}
console.log(user.email_address) // Log email_address from the user object
```

**What does Faker.js Generate?**
By logging `user.email_address` to the console, I see: `joe.smith65@gmail.com` (the numbers tend to change).
Also, the period (dot) `.` between `first_name` and `last_name` is sometimes replaced with an underscore `_` character. Also an undocumented case as far as I'm aware.

**What do I Expect to See?**
I should be seeing: `joe.smith@gmail.com` (in this case the `gmail.com` TLD was chosen, note: NO numbers).

Generating a robust email using faker is an important step in my use-case, I appreciate if somebody could let me know to mitigate this behavior. Cheers.

**Comment by ropali** [comment] 2019-06-23 07:29
It is working as intended because of how it is implemented under the hood.
**Understand how fake email generation works.**
When you provide `first_name` & `last_name ` faker first creates a username by calling the `userName` method using those two values & it randomly selects any separator for them(. OR -). See the code below for `userName` method,

```
self.userName = function (firstName, lastName) {
      var result;
      firstName = firstName || faker.name.firstName();
      lastName = lastName || faker.name.lastName();
      switch (faker.random.number(2)) {
      case 0:
          result = firstName + faker.random.number(99);
          break;
      case 1:
          result = firstName + faker.random.arrayElement([".", "_"]) + lastName;
          break;
      case 2:
          result = firstName + faker.random.arrayElement([".", "_"]) + lastName + faker.random.number(99);
          break;
      }
      result = result.toString().replace(/'/g, "");
      result = result.replace(/ /g, "");
      return result;
  };
```
So there is three possibility of generating any username. That's the reason you are getting diiferent seprator for username & sometimes a number is also appended.

**Comment by Moosh-be** [comment] 2021-02-22 06:17
@olafwrieden   reading ropali's response, the behavior is normal, so it's not a bug.

Could you close this issue to confirm it?

a priori I don't see why a case generator should restrict itself to the variety of completely plausible cases

If you have a suggestion for improvement, you can do a PR.
but IMHO I do not think it is relevant. <- the M of IMHO is very important :)

**Closed** 2021-02-22 06:22 UTC
