### ISSUE TITLE
The new return type of lorem.words is a breaking change

### ISSUE THREAD

**Issue by Jack12816** [Marak/faker.js#356] opened 2016-03-24 13:02 UTC
Hey, 

I expected a BC with upgrading to 3.1.0 because of #293. This changed the return type of `lorem.words` from array to string.

Would it be clever to roll this back and put a bugfix version upon it?

**Comment by nikita-gazarov-hs** [comment] 2016-03-24 21:44
Such a breaking change should increment the major version.

**Comment by Marak** [comment] 2016-03-24 21:47
Yeah, I'm not sure a major version change should be used for such a small difference.

From what I can remember, returning an array was a bug and never the intended behavior.

If you use `3.0.x` it should be the old behavior? I'm not sure what I could do to help with this moving forward. Let me know.

**Comment by nikita-gazarov-hs** [comment] 2016-03-24 21:54
There is no documentation for what datatype "words" is supposed to return, so there is no record of intended behaviour other than the implementation. The implementation was returning an array in 3.0.x.

I don't know what part of this breaking change is minor, honestly. It's breaking every usage of a popular method. If you follow semver, you should bundle up such breaking changes in major releases.

**Comment by Marak** [comment] 2016-03-24 21:59
Was always a bug in that in was returning array and not string. Never was the intended behavior.

If it's a problem for you, don't upgrade, or submit a pull request with a bug fix for the previous version.

**Comment by Jack12816** [comment] 2016-03-25 09:21
It broke an stable productive application with a minor upgraded of this library. If you don't follow semver, then please don't use semver notation! I would recommend to rollback the behavior or make a major version upgrade.

Even if it was always a bug, all application which makes use of it are broken by an update. You can't change the API in a breaking way and don't care about your users. Not cool at all.

**Comment by Marak** [comment] 2016-03-25 15:26
I've been asking for comments on this release for the past six months. Thanks for your feedback.

see: https://github.com/Marak/faker.js/issues/287

If you want to complain, go for it. If you want to see this changed, make a Pull Request.

Try not to mistake my lack of time for a lack of caring.

**Comment by Marak** [comment] 2016-03-25 16:55
I also haven't specified the usage of Semver for this project anywhere.

Generally for my projects anything in the `x.y.z` range could be considered breaking if `x` or `y` changes.

If you want to ensure the stability of your projects you should be locking your dependency versions anyway. 

I can't stress enough that it's not my responsibility to ensure the stability of your applications. For all my node.js production applications I'm locking npm versions to specific numbers ( no ranges ) and watching for package update alerts in a third-party system.

**Comment by Marak** [comment] 2016-03-30 06:42
I'm closing this.

Sorry if I caused anyone any real issues.

Please. Please. Please. If you are doing a continuos integration deployment that uses `package.json` at all. PLEASE lock your versions in using something like `3.0.1`. Use that same technique that for all your production packages. You can keep you development `package.json` locked into `*` for all I care.

**Closed by Marak** 2016-03-30 06:42 UTC
